---
- name: Ping
  hosts: all
  gather_facts: true
  tasks:
    - name: Ping
      become: true
      ansible.builtin.ping:
    - name: Display output
      ansible.builtin.debug:
        var: result
